module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        // módulos de negócio
        'shared',
        'tenant',
        'identity',
        'customer',
        'catalog',
        'scheduling',
        'notification',
        'audit',
        'sales',
        'finance',
        'billing',
        'analytics',
        'ai',
        'inventory',
        'workorder',
        'crm',
        'automation',
        'integration',
        // áreas
        'backend',
        'frontend',
        'docs',
        'infra',
        'ci',
        'deps',
        'release',
      ],
    ],
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
  },
};
