package com.omnia.platform.onboarding.application.usecase;

import com.omnia.platform.identity.UserAccounts;
import com.omnia.platform.shared.domain.Ids;
import com.omnia.platform.shared.tenancy.TenantContext;
import com.omnia.platform.shared.tenancy.TenantSession;
import com.omnia.platform.tenant.Tenants;
import com.omnia.platform.tenant.Vertical;
import java.util.UUID;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;

/**
 * Self-service signup: creates the tenant and its owner account in a single transaction.
 *
 * <p>A provisional tenant id is bound to {@link TenantContext} BEFORE the transaction starts so the
 * connection carries a tenant into PostgreSQL; the definitive id (created inside) replaces it for
 * the RLS-protected owner insert (ADR-003). The whole operation is atomic: any failure rolls back
 * both tenant and owner.
 */
@Service
public class SignUpTenantUseCase {

    private final Tenants tenants;
    private final UserAccounts userAccounts;
    private final TransactionTemplate transaction;
    private final TenantSession tenantSession;

    public SignUpTenantUseCase(
            Tenants tenants, UserAccounts userAccounts, TransactionTemplate transaction, TenantSession tenantSession) {
        this.tenants = tenants;
        this.userAccounts = userAccounts;
        this.transaction = transaction;
        this.tenantSession = tenantSession;
    }

    public Result execute(Command command) {
        var outcome = new Object() {
            Tenants.TenantSummary tenant;
            UUID ownerUserId;
        };
        // The tenants table is global (no RLS), but the owner insert is RLS-protected and the
        // definitive tenant id is generated by the aggregate inside the transaction. We therefore
        // rebind the transaction-local tenant setting once the id is known (TenantSession).
        UUID provisionalId = Ids.newId();
        TenantContext.runAs(
                provisionalId,
                () -> transaction.executeWithoutResult(status -> {
                    outcome.tenant = tenants.signUp(command.slug(), command.companyName(), command.vertical());
                    tenantSession.bindTransaction(outcome.tenant.id());
                    outcome.ownerUserId = userAccounts.createOwner(
                            outcome.tenant.id(), command.ownerName(), command.ownerEmail(), command.ownerPassword());
                }));
        return new Result(outcome.tenant.id(), outcome.ownerUserId, outcome.tenant.slug());
    }

    public record Command(
            String slug,
            String companyName,
            Vertical vertical,
            String ownerName,
            String ownerEmail,
            String ownerPassword) {}

    public record Result(UUID tenantId, UUID ownerUserId, String slug) {}
}
